import React from 'react';

const styles = {
  Text: {
    color: '#040000',
    fontSize: '14px',
    fontFamily: 'Poppins',
    lineHeight: '18px',
    padding: '10px',
  },
};

const defaultProps = {
  text: `This Privacy Policy describes how Claims Crafters, LLC (“Claims Crafters”) collects, uses and discloses information and what choices you have with respect to that information. It also describes how we protect the security of information. “Personal Information” as used in this Privacy Policy refers to information that personally identifies you, such as your name, mailing address, telephone number, email address and Internet Protocol (IP) address. If you have any questions or comments regarding this Privacy Policy, please contact us at support@claimscrafters.com.

Applicability of this Privacy Policy

This Privacy Policy applies to www.claimscrafters.com (the “Website”), the interactive services on the Website, including inputs for collecting user information and contents valuation creation (collectively, the “Services”), and any other interactions (i.e., customer service inquiries or social media) you may have with Claims Crafters. If you do not agree with any of the terms of this Privacy Policy, do not access the Website or use the Services.

Changes to Our Privacy Policy

We may make changes to the Privacy Policy from time to time. We will notify you of any material changes by sending you an email, posting a notice on the home page of the Website, or posting a notice in your account. If you receive notification of a change in our Privacy Policy, you should review the new policy carefully to ensure you understand our practices and procedures.

Information We Collect and Receive

Claims Crafters may collect information about you when you access or interact with the Website, sign up to use the Services, or otherwise transmit information to us. We may also obtain information about you from our business partners and affiliates, or from publicly available information. The information Claims Crafters collects includes:
When you create an account with Claims Crafters, you supply us with Personal Information such as name, mailing address, email address, phone number and company name. We also collect information necessary to use the Services and in the forms you fill out including:
· Username, password, and other login information.
· Your current address and contact information.
· Information associated with a homeowner’s claim
· Credit information and social security number when you direct us to obtain your credit report.
· Information available from publicly available records.
· Payment information for billing purposes.
· Usage information automatically collected when you access our Website or Services.
· Any other information you provide us.

Do Not Track Signals The Website does not respond to Do Not Track (DNT) signals. Third party applications and plugins, such as social media integration, may treat DNT signals differently.

No Information From Children Under Age 1 Claims Crafters’ Website is not directed to people under the age of 18 and, therefore, we do not knowingly collect Personal Information from children under the age of 18. If we learn that we have collected Personal Information from someone under the age of 18, we will promptly delete that information. If you believe we have collected Personal Information from someone under age 18, please email us at support@ claimscrafters.com.
How We Collect and Use Information

Personal Information We use Personal Information to provide the Services including establishing a new account, create a new contents valuation project, as well as maintaining, evaluating and improving the Website. We also use it to communicate with you, fulfill requests for information, deliver services, and provide user support.

Cookie A cookie is a small file containing a string of characters that is sent to your computer when you visit a website. When you visit the website again, the cookie allows that website to recognize your browser. Cookies may store unique identifiers, user preferences, and other information. When you visit our Website we send one or more “cookies” to your computer or other device. You can set your browser to refuse all cookies or to indicate when a cookie is being sent. However, some Website features or services may not function properly without cookies. We use cookies to improve the quality of the Website and Services, including to store user preferences, to track user trends, and to provide relevant advertising to you.

Google Analytics. Claims Crafters uses Google Analytics to help analyze how users use the Website. Google Analytics uses cookies to collect standard Internet log information and visitor behavior information in an anonymous form. The information generated by the cookie about your use of the Website (including IP address) is transmitted to Google. This information is then used to evaluate visitors’ use of the Website and compile statistical reports on Website activity for Claims Crafters. For more information regarding how Google Analytics protects your data, please visit Google’s website at https://support.google.com/analytics/answer/6004245?hl=en.

Additional Analytics Services: The Website may also uses the following analytics services in addition to Google Analytics: Hubspot Analytics, Mixpanel, Facebook Connect, and Segment.
How We Share and Disclose Information

Disclosure to Unaffiliated Third Parties We may disclose your Personal Information to: (i) respond to legal requirements, to protect or enforce our rights and policies, to protect or enforce the rights of a third party, to prevent harm to a person or as required or permitted by law, including, without limitation, to comply with a subpoena or court order, (ii) to third parties to market their products or services to you if you have consented to/not opted out of these disclosures, (iii) to contractors, service providers and other third parties we use to support our business.

Disclosure of Non-Personal Information We may disclose your aggregated or de-identified online information or usage data to any party including potential business partners, advertisers, investors, users, and other third parties.

Disclosure to Corporate Affiliates and Successors Claims Crafters may disclose Personal Information to its parent company, subsidiaries or other corporate affiliates, if any. If Claims Crafters engages in a merger, acquisition, reorganization, sale of some or all of its assets, or similar transaction, or takes steps in contemplation of such transactions (e.g., due diligence), Personal Information may be shared with or transferred to a new or prospective owner, subject to standard confidentiality agreements.

Disclosure With Your Consent In addition to the sharing described elsewhere in this Privacy Policy, we may share Personal Information with companies, organizations or individuals outside of Claims Crafters if we obtain your consent to do so.

Data Storage and Retention
Your Personal Information may be stored by Claims Crafters on its company servers, on its employees’ computers, or on the servers of cloud-based data storage providers. Claims Crafters retains Personal Information for the duration of a user’s business relationship with the company, for the purposes indicated in this Privacy Policy, or for such other period as may be permitted or required by law, which may be indefinitely.

Data Security
Claims Crafters takes the privacy of your information seriously. We use industry standard physical, technical and administrative security measures and safeguards to protect the confidentiality and security of Personal Information. However, since the Internet is not a 100% secure environment, we cannot guarantee the security of any information you transmit to us. Further, it is your responsibility to protect the security of your account and login information. Please note that content you store or transmit through the Website, or e-mails and other communications you send to us, are not encrypted. You should not assume that your content will be kept private, and we strongly advise you not to communicate any confidential information through these means.

Making Changes To Your Personal Information
If you have questions about your Personal Information or want to make a request to update it, you can email us at support@claimscrafters.com. You can opt-out of receiving marketing or promotional e-mails from Claims Crafters by going to the account management section of the Website, or by using the opt-out or unsubscribe feature contained in the marketing or promotional e-mails.

Third Party Websites
You may be able to access third party websites directly from the Website. This Privacy Policy does not apply when you access third party websites. We cannot control how third parties may use any information you disclose to them, so you should carefully review the privacy policy of any third party website you visit before using it or disclosing your information to its provider.
If we wish to disclose your information to a third party in a manner that is not set forth in this Privacy Policy, you will be notified so that you can make an informed choice about sharing your information.

Supplemental Notice for California Consumers

Shine the Light. Under California’s “Shine the Light” law, California residents who provide Personal Information in obtaining products or services for personal, family, or household use are entitled to request and obtain from us once a calendar year information about the customer information we shared, if any, with other businesses for their own direct marketing uses. If applicable, this information would include the categories of customer information and the names and addresses of those businesses with which we shared that information for the immediately prior calendar year (e.g., requests made in 2023 will receive information regarding 2022 sharing activities).

To obtain this information, please send an email message to support@ claimscrafters.com with “Shine the Light Request” on the subject line and in the body of your message. We will provide the requested information to you at your e-mail address in response. Please be aware that not all information sharing is covered by the “Shine the Light” requirements and only information on covered sharing will be included in our response.

California Consumer Privacy Act (“CCPA”) The CCPA provides certain rights to California residents regarding their Personal Information. A California resident has the right to request that Claims Crafters disclose certain information, including: (1) the categories of Personal Information it has collected about that California resident, (2) the categories of sources from which the Personal Information is collected, (3) the business or commercial purpose for collecting or selling the Personal Information, (4) the categories of third parties with whom Claims Crafters shares Personal Information, (5) the specific pieces of Personal Information it has collected about that resident, and (6) the categories of Personal Information that Claims Crafters has sold about that resident and the categories of third parties to whom that information was sold.

A California resident has the right to request that Claims Crafters delete their Personal Information. A California resident also has a right to “opt-out” of the sale of that resident’s personal information. Finally, a California resident has the right not to be discriminated against for exercising their privacy rights under the CCPA. Provided, however, that the CCPA does not prohibit Claims Crafters from offering financial incentives, different prices, rates, levels or qualities of goods or services for the collection of personal information if that price or difference is directly related to the value provided by the consumer’s data.

To submit a request to exercise your rights as a California resident, please submit the details of your request through Do Not Sell My Personal Information link here or by email to privacy@Claims Crafters.com, with the subject line “CCPA Consumer Request.” You may designate an agent to submit requests on your behalf by emailing privacy@Claims Crafters.com with the header “Designated Agent – CCPA Consumer Request” and including that person’s contact information.

Claims Crafters has collected and/or disclosed for a business purpose within the last 12 months the categories of Personal Information about California consumers indicated below:
































Sales of Information. California’s broad definition of “sale” may include sharing information for certain online advertising or reporting information to Claims Adjusters, Insurance Carriers and/or their affiliates when appropriate for Claims Crafters’ services. While Claims Crafters may share any of the Personal Information it collects for those purposes, it does not otherwise “sell” any consumers’ personal information. 

Sources of Information. Claims Crafters has collected the above categories of California consumers’ Personal Information from the following sources:
· Directly from you. For example, from forms you complete or services you use.
· Indirectly from you. For example, from observing your actions on our Website.
· From third parties. For example, from Claims Adjusters, Insurance Carriers and/or their affiliates.

Commercial Purpose for Collection. Claims Crafters collects California consumers’ Personal Information for the purposes enumerated in this Privacy Policy, as discussed in detail above, including to communicate with customers concerning our services, providing the Website and Services, and improving the Website and Services.

Categories of Third Parties We Disclose Information To. Claims Crafters discloses for a business purpose information to the following third parties:
· Subprocessors, such as cloud hosting websites or payment processors, to facilitate the functioning of the Website.
· Marketing services, to provide relevant advertising to potential and existing customers.



















































































































',`
};

const Text = (props) => {
  return (
    <div style={styles.Text}>
      {props.text ?? defaultProps.text}
    </div>
  );
};

export default Text;